server:
  port: 8080
spring:
  application:
    name: "worklog-database-sync"
  datasource:
    jira: # Jira Datasource
      driver-class-name: org.postgresql.Driver
      hikari:
        maximumPoolSize: 5
        connectionTimeout: 20000
        idleTimeout: 600000
        maxLifetime: 1800000
      url: jdbc:postgresql://tibia.entimo.de:5432/jiradb
      username: postgres
      password: entimo1
    pep: # PEP Datasource
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@pepe.entimo.de:1521/pep.entimo.de
      username: system
      password: manager1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
springdoc:
  api-docs:
    path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      operationsSorter: method
timer:
# start timer when application starts
  startTimerAtStartup: false
# sync period in minutes
  timerSyncPeriod: 1
# sync only once per day at 12p - the sync period will be ignored
  syncOncePerDay: false

# number of last days to check for work logs in one scan
daysToScan: 21
